name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy files to server using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: organizer.w3.pm2etml.ch
          username: mustafa-ssh
          password: ${{ secrets.ORGANIZER_DEPLOY }}
          port: 222
          source: "./"
          target: "htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer"
          strip_components: 1
          overwrite: true
          rm: true
          command_timeout: 30m

      - name: Set Correct Permissions & Restart Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: organizer.w3.pm2etml.ch
          username: mustafa-ssh
          password: ${{ secrets.ORGANIZER_DEPLOY }}
          port: 222
          script: |
            cd /htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer
            echo php artisan migrate
            echo php artisan optimize:clear
