name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      #TODO vite build!!! (attention) OK!
      - name: Clean node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm package-lock.json

      - name: Install dependencies
        run: npm install
  
      - name: Build project
        run: npm run build

      - name: Deploy files to server using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: organizer.w3.pm2etml.ch
          username: mustafa-ssh
          password: ${{ secrets.ORGANIZER_DEPLOY }}
          port: 222
          source: "./public/build/cd"   # <-- important : le dossier des fichiers build (vite fait du dossier 'dist' le dossier par défaut)
          target: "htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer/build"
          strip_components: 1
          overwrite: true
          command_timeout: 30m


      - name: Set Correct Permissions & Restart Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: organizer.w3.pm2etml.ch
          username: mustafa-ssh
          password: ${{ secrets.ORGANIZER_DEPLOY }}
          port: 222
          script: |
            cd htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer
            php artisan migrate
            php artisan optimize:clear
