name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Clean node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm package-lock.json

      - name: Install dependencies
        run: npm install
  
      - name: Build project
        run: npm run build

      - name: Sync project to server
        run: sshpass -p "${{ secrets.ORGANIZER_DEPLOY }}" rsync -avz 
            -e "ssh -p 222 -o StrictHostKeyChecking=no" 
            --exclude "node_modules"
            --exclude ".git"  
            --exclude ".env" 
            ./ 
            mustafa-ssh@organizer.w3.pm2etml.ch:htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer

      - name: Run Laravel commands
        run: sshpass -p "${{ secrets.ORGANIZER_DEPLOY }}" ssh -o StrictHostKeyChecking=no -p 222 mustafa-ssh@organizer.w3.pm2etml.ch '
            cd htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer &&
            composer install --no-dev --optimize-autoloader &&
            php artisan optimize:clear &&
            php artisan migrate --force &&
          '