name: Deploy Laravel to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, bcmath

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      
      - name: Generate application key
        run: php artisan key:generate --force
      
      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 222
          source: "./"
          target: "htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer"
          strip_components: 1
          overwrite: true
          rm: true
          tar_tmp_path: "/tmp"
          command_timeout: 10m

      - name: Run migrations
        run: |
          php artisan migrate --force
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASS }}
