name: Deploy Laravel via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, bcmath

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      
      - name: Generate application key
        run: php artisan key:generate --force
      
      - name: Deploy files via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: organizer.w3.pm2etml.ch
          username: mustafa-ssh
          password: 5bZprPw3CYN15mrKHU4B
          port: 222
          source: "./"
          target: "htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer"
          strip_components: 1

      - name: Run migrations via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: organizer.w3.pm2etml.ch
          username: mustafa-ssh
          password: 5bZprPw3CYN15mrKHU4B
          port: 222
          script: |
            cd htdocs/organizer.w3.pm2etml.ch/public/pretpi24-organizer
            php artisan migrate --force
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: organizer
          DB_USERNAME: orguser
          DB_PASSWORD: tmGgkvvrmz2PXU7a7VfV
